edit: prisma migrate 과정 대기 설정 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -103,17 +103,23 @@ jobs:
           sudo docker stop devlog || true
           sudo docker rm devlog || true
 
-          # Prisma 마이그레이션 실행
-          sudo docker run --rm \
-            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
-            ${{ steps.build-image.outputs.image }} \
-            npx prisma migrate deploy
+          # 기존 마이그레이션 컨테이너 중지 (존재한다면)
+          sudo docker stop devlog-migration || true
 
-          # 애플리케이션 실행
-          sudo docker run -d --name devlog -p 3000:3000 \
-            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
-            ${{ steps.build-image.outputs.image }}
+          # Prisma 마이그레이션 실행 (컨테이너 유지)
+          sudo docker run -d --name devlog-migration ${{ steps.build-image.outputs.image }} npx prisma migrate deploy
 
+          # 마이그레이션 완료 대기
+          sudo docker wait devlog-migration
+
+          # 마이그레이션 결과 확인
+          if [ $(sudo docker inspect -f '{{.State.ExitCode}}' devlog-migration) -ne 0 ]; then
+            echo "Migration failed. Check the migration logs."
+            exit 1
+          fi
+
+          # 애플ㄹ리케이션 컨테이너 실행
+          sudo docker run -d --name devlog -p 3000:3000 ${{ steps.build-image.outputs.image }}
 
           # Nginx 설정이 올바른지 확인
           sudo nginx -t
